export const MNO_METADATA_RESULT = {
  '10017': {
    mno: 'AT&T',
    mnoSupport: true,
    mnoReview: false,
    qualify: true,
    minMsgSamples: 1,
    reqSubscriberOptin: true,
    reqSubscriberOptout: true,
    reqSubscriberHelp: true,
    noEmbeddedLink: false,
    noEmbeddedPhone: false,
    surcharge: null,
    msgClass: 'A',
    tpm: 4500,
    brandTier: null,
  },
  '10035': {
    mno: 'T-Mobile',
    mnoSupport: true,
    mnoReview: false,
    qualify: true,
    minMsgSamples: 1,
    reqSubscriberOptin: true,
    reqSubscriberOptout: false,
    reqSubscriberHelp: true,
    noEmbeddedLink: false,
    noEmbeddedPhone: false,
    surcharge: null,
    msgClass: null,
    tpm: null,
    brandTier: 'TOP',
  },
  '10037': {
    mno: 'US Cellular',
    mnoSupport: true,
    mnoReview: false,
    qualify: true,
    minMsgSamples: 1,
    reqSubscriberOptin: false,
    reqSubscriberOptout: false,
    reqSubscriberHelp: false,
    noEmbeddedLink: false,
    noEmbeddedPhone: false,
    surcharge: null,
    msgClass: null,
    tpm: null,
    brandTier: null,
  },
  '10038': {
    mno: 'Verizon Wireless',
    mnoSupport: true,
    mnoReview: false,
    qualify: true,
    minMsgSamples: 1,
    reqSubscriberOptin: false,
    reqSubscriberOptout: false,
    reqSubscriberHelp: false,
    noEmbeddedLink: false,
    noEmbeddedPhone: false,
    surcharge: null,
    msgClass: null,
    tpm: null,
    brandTier: null,
  },
};
